# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "functions/"
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# Redirects About page to Who We Are page
[[redirects]]
    from = "https://www.mdhconstruction.com/about"
    to = "https://www.mdhconstruction.com/who-we-are"
    status = 301
    force = true

# Redirects About page to Who We Are page
[[redirects]]
    from = "https://www.mdhconstruction.com/login"
    to = "https://www.mdhconstruction.com"
    status = 301
    force = true

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true